### ISSUE TITLE
"renegade bbs old site"

### ISSUE THREAD

**Issue by mro1337** [renegadebbs/renegade#12]
What do you mean "old site" ??

**Comment by sikofitt** [comment]
Where are you seeing that?

**Comment by mro1337** [comment]
also please remove the link to renegadebbs.info  from renegade.cc ; the one that refers to it as a legacy website

**Comment by sikofitt** [comment]
No problem, but it doesn't seem to be updated, so I figured it was legacy.

**Comment by mro1337** [comment]
i dont care what you call it, dont link to it please.  
this is what i mean by 'old site'
![rg old site screenshot - oct 11 2017 4 35 pm](https://user-images.githubusercontent.com/745863/31468192-59b86ada-aea2-11e7-9098-50bcd356bb97.png)

**Comment by sikofitt** [comment]
Oh I see.  It's removed but honestly, I can link to whatever I want on the internet.   So chill out.
